CREATE DATABASE IF NOT EXISTS ms_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ms_productos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ms_pedidos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

